#ifndef HHTP_METHODE

# define HTTP_METHODE


# define MAX_HTTP_CODE 511

# define XX(a, b, c) (struct t_methode){a, b, c}

struct t_methode {
	int	number;
	char	*name;
};

# define METHODE_ARRAY (struct t_methode[]) {	\
	XX(100, "CONTINUE")							\
	XX(101, "SWITCHING_PROTOCOLS")				\
	XX(102, "PROCESSING")						\
	XX(200, "OK")								\
	XX(201, "CREATED")							\
	XX(202, "ACCEPTED")							\
	XX(203, "NON_AUTHORITATIVE_INFORMATION")	\
	XX(204, "NO_CONTENT")						\
	XX(205, "RESET_CONTENT")					\
	XX(206, "PARTIAL_CONTENT")					\
	XX(207, "MULTI_STATUS")						\
	XX(208, "ALREADY_REPORTED")					\
	XX(226, "IM_USED")							\
	XX(300, "MULTIPLE_CHOICES")					\
	XX(301, "MOVED_PERMANENTLY")				\
	XX(302, "FOUND")							\
	XX(303, "SEE_OTHER")						\
	XX(304, "NOT_MODIFIED")						\
	XX(305, "USE_PROXY")						\
	XX(307, "TEMPORARY_REDIRECT")				\
	XX(308, "PERMANENT_REDIRECT")				\
	XX(400, "BAD_REQUEST")						\
	XX(401, "UNAUTHORIZED")						\
	XX(402, "PAYMENT_REQUIRED")					\
	XX(403, "FORBIDDEN")						\
	XX(404, "NOT_FOUND")						\
	XX(405, "METHOD_NOT_ALLOWED")				\
	XX(406, "NOT_ACCEPTABLE")					\
	XX(407, "PROXY_AUTHENTICATION_REQUIRED")	\
	XX(408, "REQUEST_TIMEOUT")					\
	XX(409, "CONFLICT")							\
	XX(410, "GONE")								\
	XX(411, "LENGTH_REQUIRED")					\
	XX(412, "PRECONDITION_FAILED")				\
	XX(413, "PAYLOAD_TOO_LARGE")				\
	XX(414, "URI_TOO_LONG")						\
	XX(415, "UNSUPPORTED_MEDIA_TYPE")			\
	XX(416, "RANGE_NOT_SATISFIABLE")			\
	XX(417, "EXPECTATION_FAILED")				\
	XX(421, "MISDIRECTED_REQUEST")				\
	XX(422, "UNPROCESSABLE_ENTITY")				\
	XX(423, "LOCKED")							\
	XX(424, "FAILED_DEPENDENCY")				\
	XX(426, "UPGRADE_REQUIRED")					\
	XX(428, "PRECONDITION_REQUIRED")			\
	XX(429, "TOO_MANY_REQUESTS")				\
	XX(431, "REQUEST_HEADER_FIELDS_TOO_LARGE")	\
	XX(451, "UNAVAILABLE_FOR_LEGAL_REASONS")	\
	XX(500, "INTERNAL_SERVER_ERROR")			\
	XX(501, "NOT_IMPLEMENTED")					\
	XX(502, "BAD_GATEWAY")						\
	XX(503, "SERVICE_UNAVAILABLE")				\
	XX(504, "GATEWAY_TIMEOUT")					\
	XX(505, "HTTP_VERSION_NOT_SUPPORTED")		\
	XX(506, "VARIANT_ALSO_NEGOTIATES")			\
	XX(507, "INSUFFICIENT_STORAGE")				\
	XX(508, "LOOP_DETECTED")					\
	XX(510, "NOT_EXTENDED")						\
	XX(511, "NETWORK_AUTHENTICATION_REQUIRED")	\
}

# undef XX

#endif
